# Generated by Django 5.0.4 on 2024-08-15 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='department_type',
            field=models.CharField(choices=[('Self', 'Self'), ('Aided', 'Aided'), ('Cell', 'Cell'), ('Committee', 'Committee')], db_index=True, max_length=225),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='role',
            field=models.CharField(choices=[('Secretary', 'Secretary'), ('Principal', 'Principal'), ('Initiator', 'Initiator'), ('Office Superintendent', 'Office Superintendent'), ('Department', 'Department'), ('Admin', 'Admin'), ('Cell', 'Cell'), ('Committee', 'Committee')], db_index=True, max_length=225),
        ),
    ]
