# Generated by Django 5.0.4 on 2024-08-15 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inward', '0001_initial'),
        ('users', '0002_alter_department_department_type_alter_userrole_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inwerd_from', models.CharField(db_index=True, max_length=225)),
                ('subject', models.CharField(max_length=225)),
                ('content', models.TextField(blank=True, null=True)),
                ('file', models.FileField(upload_to='uploads/')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('to', models.ManyToManyField(related_name='inward', to='users.department')),
            ],
        ),
        migrations.DeleteModel(
            name='UploadedFile',
        ),
    ]
