# Generated by Django 5.0.4 on 2024-08-15 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inward', '0003_rename_inwerd_from_inward_inward_from'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Inward',
        ),
    ]
