# Generated by Django 5.0.4 on 2024-08-15 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inward', '0004_uploadedfile_delete_inward'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='inward_from',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
