# Generated by Django 5.0.4 on 2024-08-15 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inward', '0005_uploadedfile_inward_from'),
        ('users', '0002_alter_department_department_type_alter_userrole_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='inward_to',
            field=models.ManyToManyField(to='users.department'),
        ),
    ]
