# Generated by Django 5.0.4 on 2024-08-15 11:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inward', '0006_uploadedfile_inward_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedfile',
            name='uploaded_at',
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='subject',
            field=models.CharField(default=1, max_length=225),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
